# CloudNap Configuration File
# Configuración para gestión de clusters de Huawei Cloud
#
# IMPORTANTE: Todos los horarios (cron expressions) están en UTC
# Para convertir a tu zona horaria local, resta/agrega las horas correspondientes
# Ejemplo: UTC+8 (Singapur) = UTC + 8 horas

# Configuración de Huawei Cloud
huawei_cloud:
  region: "la-south-2"  # Región de Huawei Cloud
  access_key: "huawei_access_key"  # Docker secret name
  secret_key: "huawei_secret_key"  # Docker secret name
  project_id: "huawei_project_id"  # Docker secret name

# Configuración de la aplicación
app:
  debug: false
  host: "0.0.0.0"
  port: 7180
  log_level: "INFO"

# Configuración de logging
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "logs/cloudnap.log"
  max_size: "10MB"
  backup_count: 5

# Clusters a gestionar
clusters:
  - name: "scoreappv2dockerqa-worker-2"
    instance_ids:
      - "0855eaf1-c0a3-4674-9b32-b1d472ae4efe"
    region: "la-south-2"
    description: "Cluster de QA para aplicaciones"
    tags:
      - "qa"
    schedule:
      wake_up: "0 4 * * 1-5"  # Lunes a Viernes a las 4:00 AM UTC
      shutdown: "0 10 * * 1-5"  # Lunes a Viernes a las 10:00 AM UTC
    enabled: true

# Configuración del scheduler
scheduler:
  timezone: "UTC"
  max_workers: 4
  coalesce: true
  misfire_grace_time: 60
