# CloudNap Configuration File
# Configuración para gestión de clusters de Huawei Cloud
#
# IMPORTANTE: Todos los horarios (cron expressions) están en UTC
# Para convertir a tu zona horaria local, resta/agrega las horas correspondientes
# Ejemplo: UTC+8 (Singapur) = UTC + 8 horas

# Configuración de Huawei Cloud
huawei_cloud:
  region: "ap-southeast-1"  # Región de Huawei Cloud
  access_key: "${HUAWEI_ACCESS_KEY}"  # Variable de entorno
  secret_key: "${HUAWEI_SECRET_KEY}"  # Variable de entorno
  project_id: "${HUAWEI_PROJECT_ID}"  # Variable de entorno

# Configuración de la aplicación
app:
  debug: false
  host: "0.0.0.0"
  port: 7180
  log_level: "INFO"

# Configuración de logging
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "logs/cloudnap.log"
  max_size: "10MB"
  backup_count: 5

# Clusters a gestionar
clusters:
  - name: "production-web-cluster"
    instance_ids:
      - "i-1234567890abcdef0"
      - "i-1234567890abcdef1"
      - "i-1234567890abcdef2"
    region: "ap-southeast-1"
    description: "Cluster de producción para aplicaciones web"
    tags:
      - "production"
    schedule:
      wake_up: "0 4 * * 1-5"  # Lunes a Viernes a las 4:00 AM UTC
      shutdown: "0 10 * * 1-5"  # Lunes a Viernes a las 10:00 AM UTC
    enabled: true
  - name: "test-cluster-1"
    instance_ids:
      - "i-test-001-a"
      - "i-test-001-b"
    region: "ap-southeast-1"
    description: "Cluster de prueba 1 para desarrollo"
    tags:
      - "test"
      - "dev"
    schedule:
      wake_up: "0 8 * * 1-5"  # Lunes a Viernes a las 8:00 AM UTC
      shutdown: "0 18 * * 1-5" # Lunes a Viernes a las 6:00 PM UTC
    enabled: true
  - name: "test-cluster-2"
    instance_ids:
      - "i-test-002-x"
      - "i-test-002-y"
    region: "ap-southeast-1"
    description: "Cluster de prueba 2 para QA"
    tags:
      - "test"
      - "qa"
    schedule:
      wake_up: "30 9 * * 1-5" # Lunes a Viernes a las 9:30 AM UTC
      shutdown: "30 17 * * 1-5" # Lunes a Viernes a las 5:30 PM UTC
    enabled: true
  - name: "test-cluster-3"
    instance_ids:
      - "i-test-003-1"
    region: "ap-southeast-1"
    description: "Cluster de prueba 3, solo un servidor"
    tags:
      - "test"
      - "single"
    schedule:
      wake_up: "0 7 * * *"    # Todos los días a las 7:00 AM UTC
      shutdown: "0 20 * * *"  # Todos los días a las 8:00 PM UTC
    enabled: true
  - name: "test-cluster-4"
    instance_ids:
      - "i-test-004-alpha"
      - "i-test-004-beta"
      - "i-test-004-gamma"
    region: "ap-southeast-1"
    description: "Cluster de prueba 4 con múltiples instancias"
    tags:
      - "test"
      - "multi"
    schedule:
      wake_up: "0 6 * * 2,4"  # Martes y Jueves a las 6:00 AM UTC
      shutdown: "0 16 * * 2,4" # Martes y Jueves a las 4:00 PM UTC
    enabled: true
  - name: "test-cluster-5"
    instance_ids:
      - "i-test-005-main"
    region: "ap-southeast-1"
    description: "Cluster de prueba 5 para tareas nocturnas"
    tags:
      - "test"
      - "nightly"
    schedule:
      wake_up: "0 22 * * *"   # Todos los días a las 10:00 PM UTC
      shutdown: "0 2 * * *"   # Todos los días a las 2:00 AM UTC
    enabled: true
  - name: "test-cluster-6"
    instance_ids:
      - "i-test-006-db"
      - "i-test-006-cache"
    region: "ap-southeast-1"
    description: "Cluster de prueba 6 para base de datos y caché"
    tags:
      - "test"
      - "db"
    schedule:
      wake_up: "0 5 * * 1-5"  # Lunes a Viernes a las 5:00 AM UTC
      shutdown: "0 19 * * 1-5" # Lunes a Viernes a las 7:00 PM UTC
    enabled: true
  - name: "test-cluster-7"
    instance_ids:
      - "i-test-007-worker"
    region: "ap-southeast-1"
    description: "Cluster de prueba 7 para workers de procesamiento"
    tags:
      - "test"
      - "worker"
    schedule:
      wake_up: "0 1 * * *"    # Todos los días a la 1:00 AM UTC
      shutdown: "0 3 * * *"   # Todos los días a las 3:00 AM UTC
    enabled: true
  - name: "test-cluster-8"
    instance_ids:
      - "i-test-008-frontend"
      - "i-test-008-backend"
    region: "ap-southeast-1"
    description: "Cluster de prueba 8 para frontend y backend"
    tags:
      - "test"
      - "web"
    schedule:
      wake_up: "0 9 * * 1-5"  # Lunes a Viernes a las 9:00 AM UTC
      shutdown: "0 17 * * 1-5" # Lunes a Viernes a las 5:00 PM UTC
    enabled: true
  - name: "test-cluster-9"
    instance_ids:
      - "i-test-009-staging"
    region: "ap-southeast-1"
    description: "Cluster de prueba 9 para staging"
    tags:
      - "test"
      - "staging"
    schedule:
      wake_up: "0 10 * * 1-5" # Lunes a Viernes a las 10:00 AM UTC
      shutdown: "0 16 * * 1-5" # Lunes a Viernes a las 4:00 PM UTC
    enabled: true
  - name: "test-cluster-10"
    instance_ids:
      - "i-test-010-misc"
      - "i-test-010-extra"
    region: "ap-southeast-1"
    description: "Cluster de prueba 10 para varios usos"
    tags:
      - "test"
      - "misc"
    schedule:
      wake_up: "0 11 * * 3"   # Miércoles a las 11:00 AM UTC
      shutdown: "0 15 * * 3"  # Miércoles a las 3:00 PM UTC
    enabled: true
  - name: "staging-api-cluster"
    instance_ids:
      - "i-staging-api-001"
      - "i-staging-api-002"
    region: "ap-southeast-1"
    description: "Cluster de staging para APIs"
    tags:
      - "staging"
      - "api"
      - "backend"
    schedule:
      wake_up: "0 2 * * 1-5"  # Lunes a Viernes a las 2:00 AM UTC
      shutdown: "0 12 * * 1-5"  # Lunes a Viernes a las 12:00 PM UTC
    enabled: true
  - name: "monitoring-cluster"
    instance_ids:
      - "i-monitoring-001"
    region: "ap-southeast-1"
    description: "Cluster para monitoreo y alertas"
    tags:
      - "monitoring"
      - "infrastructure"
      - "24x7"
    schedule:
      wake_up: "0 0 * * *"  # Todos los días a medianoche UTC
      shutdown: "0 23 * * *"  # Todos los días a las 11:00 PM UTC
    enabled: true
  - name: "data-processing-cluster"
    instance_ids:
      - "i-data-001"
      - "i-data-002"
      - "i-data-003"
    region: "ap-southeast-1"
    description: "Cluster para procesamiento de datos"
    tags:
      - "data"
      - "processing"
      - "analytics"
    schedule:
      wake_up: "0 1 * * 1"  # Lunes a la 1:00 AM UTC
      shutdown: "0 18 * * 5"  # Viernes a las 6:00 PM UTC
    enabled: true
  - name: "backup-cluster"
    instance_ids:
      - "i-backup-001"
      - "i-backup-002"
    region: "ap-southeast-1"
    description: "Cluster para backups y almacenamiento"
    tags:
      - "backup"
      - "storage"
      - "infrastructure"
    schedule:
      wake_up: "0 2 * * 1"  # Lunes a las 2:00 AM UTC
      shutdown: "0 20 * * 5"  # Viernes a las 8:00 PM UTC
    enabled: true
  - name: "development-cluster"
    instance_ids:
      - "i-dev-001"
      - "i-dev-002"
      - "i-dev-003"
    region: "ap-southeast-1"
    description: "Cluster de desarrollo para testing"
    tags:
      - "development"
      - "testing"
      - "dev"
    schedule:
      wake_up: "0 8 * * 1-5"  # Lunes a Viernes a las 8:00 AM UTC
      shutdown: "0 18 * * 1-5"  # Lunes a Viernes a las 6:00 PM UTC
    enabled: true
  - name: "analytics-cluster"
    instance_ids:
      - "i-analytics-001"
      - "i-analytics-002"
    region: "ap-southeast-1"
    description: "Cluster para análisis de datos y reportes"
    tags:
      - "analytics"
      - "reporting"
      - "data"
    schedule:
      wake_up: "0 1 * * 1"  # Lunes a la 1:00 AM UTC
      shutdown: "0 17 * * 5"  # Viernes a las 5:00 PM UTC
    enabled: true

# Configuración del scheduler
scheduler:
  timezone: "UTC"
  max_workers: 4
  coalesce: true
  misfire_grace_time: 60
